version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__cString: "Server=db;Database=NeftchiLLC;User Id=sa;Password=Query123;MultipleActiveResultSets=true;TrustServerCertificate=true;"
    networks:
      - neftchi-net

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Query123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    networks:
      - neftchi-net

networks:
  neftchi-net:
