version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__cString: "Server=tcp:alizadehh.database.windows.net,1433;Initial Catalog=Alizadehh;Persist Security Info=False;User ID=sqladmin;Password=Tengri541!;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
